// <auto-generated />
namespace BusinessTripAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTags));
        
        string IMigrationMetadata.Id
        {
            get { return "201905311054272_AddTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
